version: '3.8'

services:

  # Векторная база данных Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__CLUSTER__ENABLED=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://qdrant:6333/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - mcp-network

  # Сервис эмбеддингов
  embedding-service:
    build: ./embeddings
    container_name: embedding-service
    ports:
      - "5000:5000"
    volumes:
      - ./embeddings/config.json:/app/config.json:ro
      - ./embeddings/models:/root/.cache/huggingface/hub
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://embedding-service:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Longer start period for model loading
    restart: unless-stopped
    networks:
      - mcp-network

  # Сервис загрузки данных
  loader:
    build: ./loader
    container_name: loader
    ports:
      - "8501:8501"
    environment:
      - EMBEDDING_SERVICE_URL=http://embedding-service:5000
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
      - embedding-service
    networks:
      - mcp-network

  # MCP RAG сервер
  mcp-server:
    build: ./mcp
    container_name: mcp-server
    ports:
      - "8000:8000"
    environment:
      - EMBEDDING_SERVICE_URL=http://embedding-service:5000
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SERVER_PORT=8000
    depends_on:
      - qdrant
      - embedding-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://mcp-server:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-inspector:
    build: ./inspector
    container_name: mcp-inspector
    ports:
      - "6274:6274"   # UI
      - "6277:6277"   # MCP Proxy
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
